### ISSUE TITLE
Question For Training Dataset

### ISSUE THREAD

**Issue by dumpmemory** [Langboat/mengzi-retrieval-lm#9]
Except the database and index data on huggingface, the train_data.json in the repo could thought to be an example right? Would you mind releasing the full version of train and test dataset for reproducing the result ?

**Comment by bling0830** [comment]
We explain how to retrieve the library and how to handle training data in [index-server/README.md](https://github.com/Langboat/mengzi-retrieval-lm/blob/main/index-server/README.md). The pile is used as training corpus.

We used the first 400,000 texts of pile_00.json and the first 400,000 texts of pile_29.json for a total of 800,000 texts as training corpus. Do the truncate operation for text over 1025.

**Comment by dumpmemory** [comment]
Thanks for your support.
